---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users
  labels:
    name: users
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
      - name: users
        image: microshop/users:latest
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: users-db:27017
        - name: JAVA_OPTS
          value: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
