---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users
  labels:
    name: users
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
      - name: users
        image: microshop/users:latest
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: MONGO_HOST
          value: users-db:27017
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
